### ISSUE TITLE
Stienen plot

### ISSUE THREAD

**Issue by carbonmetrics** [spatstat/book#1]
I have two questions related to the Stienen diagram. 

The book (p260) and `?stienen` define the construction of the diagram as:

> ...formed by drawing a circle around each point of the pattern, with diameter equal to the nearest-neighbour distance for that point. These circles do not overlap. The code on p260:

`plot(X %mark% nndist(X), markscale=1)`

`?nndist` however suggests:

```
# Stienen diagram
 plot(cells %mark% (nndist(cells)/2), markscale=1)
```

The latter definition looks right to me, as you have to work with the radius (or d/2) and not with the diameter if you don't want overlapping circles.

Related:
In my dataset (attached) I can plot `stienen` but I can't get a Stienen set:

```
> stienenSet(snares)
Error in disc(d[i], X[i], delta = delta) : radius > 0 is not TRUE
```
[myppp.zip](https://github.com/spatstat/book/files/3126075/myppp.zip)

**Comment by baddstats** [comment]
This website is not meant for answering readers' questions about the book. Please email the book authors directly if you have questions.

If the disc diameter is equal to the nearest-neighbour distance, this means that the disc radius is half the nearest-neighbour distance, so the statement in the book and in the help for `stienen` is correct.

The example code in `nndist` is out-of-date. If you had executed the line `plot(cells %mark% (nndist(cells)/2), markscale=1)` in any recent version of `spatstat` (later than 2014), this would not produce the Stienen diagram; the discs are half as large as they should have been. Thank you for alterting us to this - it will be corrected in the next release.

Your last issue is a bug (which should have been posted as an issue for `spatstat/spatstat`). It will be fixed shortly.

**Comment by carbonmetrics** [comment]
Thanks! I have sent a mail directly to one of the authors once but did not get a reply.
